Add core dump files to gitignore and improve docker build
Co-authored-by: langleyreview <langleyreview@gmail.com>

diff --git a/docker/pylith-testenv b/docker/pylith-testenv
--- a/docker/pylith-testenv
+++ b/docker/pylith-testenv
@@ -2,7 +2,7 @@
 
 # BUILD CIG DEPENDENCIES ----------
 ARG BASE_IMAGE
-from ${BASE_IMAGE} as base
+FROM ${BASE_IMAGE} AS base
 ARG REPO_DIR=.
 ARG TEST_COVERAGE=no
 ARG PYTHON_COVERAGE=coverage3
@@ -46,7 +46,16 @@ RUN ${src_dir}/configure --enable-testing --enable-swig --prefix=${INSTALL_DIR} 
 # ------------------------------------------------------------------------------
 ENV PETSC_DIR=${INSTALL_DIR}/petsc  PETSC_ARCH=arch-pylith
 
-RUN git clone --branch knepley/pylith --single-branch https://gitlab.com/petsc/petsc.git ${PETSC_DIR}
+RUN set -e; \
+    for attempt in 1 2 3 4 5; do \
+      if git clone --branch knepley/pylith --single-branch https://gitlab.com/petsc/petsc.git "${PETSC_DIR}"; then \
+        break; \
+      fi; \
+      echo "WARNING: PETSc clone failed (attempt ${attempt}); retrying..." >&2; \
+      rm -rf "${PETSC_DIR}"; \
+      sleep $((attempt * 15)); \
+    done; \
+    test -d "${PETSC_DIR}/.git"
 WORKDIR ${PETSC_DIR}
 
 RUN python3 ./configure --download-parmetis=1 --download-metis=1 --download-ml=1 --download-f2cblaslapack=1 --with-hdf5=1 --with-hdf5-include=${HDF5_INCDIR} --with-hdf5-lib=${HDF5_LIBDIR}/libhdf5.so --with-zlib=1 --LIBS=-lz --with-debugging=1 --with-fc=0 --with-64-bit-points=1 --with-large-file-io=1 CPPFLAGS="-I${INSTALL_DIR}/include" LDFLAGS="-L${INSTALL_DIR}/lib" CFLAGS="-g -O" && make -j$(nproc) && make check
@@ -55,7 +64,7 @@ RUN python3 ./configure --download-parmetis=1 --download-metis=1 --download-ml=1
 # ------------------------------------------------------------------------------
 # Install pylith
 # ------------------------------------------------------------------------------
-from base as src
+FROM base AS src
 
 ENV  src_dir=${TOPSRC_DIR}/pylith  build_dir=${TOPBUILD_DIR}/pylith
 
@@ -68,14 +77,14 @@ WORKDIR ${build_dir}
 RUN ${src_dir}/configure --prefix=${INSTALL_DIR} --enable-hdf5 --enable-cubit --enable-testing --enable-swig --enable-test-coverage=${TEST_COVERAGE} --with-python-coverage=${PYTHON_COVERAGE} CPPFLAGS="-I${INSTALL_DIR}/include -I${HDF5_INCDIR}" LDFLAGS="-L${INSTALL_DIR}/lib -L${INSTALL_DIR}/lib64 -L${HDF5_LIBDIR} --coverage" CXXFLAGS="-g -O --coverage" CC=mpicc CXX=mpicxx
 
 # ----------------------------------------
-from src as build
+FROM src AS build
 RUN make -j$(nproc) install && make dist
 
 
 WORKDIR ${src_dir}
 
 # ----------------------------------------
-from build as test
+FROM build AS test
 
 WORKDIR ${build_dir}
 RUN make clean-coverage && make -j$(nproc) check VERBOSE=1 -C tests/libtests && make coverage-libtests
